apiVersion: apps/v1
kind: Deployment

metadata:
  name: go-web-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: go-web-app

  template:
    metadata:
      labels:
        app: go-web-app

    spec:
      containers:
        - name: go-web-app
          image: yashu2026/go-web-app:ab0dcd40748eeea42432ea60abad67919654a1cf
          ports:
            - containerPort: 8080