name: Docker CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.22"

      - name: Run Go tests
        run: go test ./...

      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name == 'push' }}
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/go-web-app:latest
            ${{ secrets.DOCKER_USERNAME }}/go-web-app:${{ github.sha }}

      - name: Update Kubernetes image
        if: github.event_name == 'push'
        run: |
          sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/go-web-app:${{ github.sha }}|" k8s/manifests/deployment.yaml

      - name: Commit and push Kubernetes manifest
        if: github.event_name == 'push'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add k8s/manifests/deployment.yaml

          if git diff --cached --quiet; then
            echo "No Kubernetes manifest changes."
            exit 0
          fi

          git commit -m "Update Docker image to ${GITHUB_SHA}"
          git push
